name: Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  coverage:
    name: Recalculate Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: ./.github/wiki/

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Test
        run: go test ./...

      - name: Generate Coverage Report
        shell: bash
        run: |
          ./.github/scripts/coverage.sh ./.github/wiki/

      - name: Push to Wiki
        shell: bash
        run: |
          cd ./.github/wiki/
          git add --all
          git diff-index --quiet HEAD && exit
          git config --local user.name  "GitHub Action"
          git config --local user.email "action@github.com"
          git commit --amend --no-edit && git push --force-with-lease || \
            git commit -m "Update coverage" && git push
